### ISSUE TITLE
Jsonb org.hibernate.MappingException

### ISSUE THREAD

**Issue by wolandec** [kaleidos/grails-postgresql-extensions#79]
Hi.

I tried to use Jsonb property in domain, using your extention. I did all steps exactly as described in documentation. But when server starting I have an Exception.

ERROR org.hibernate.tool.hbm2ddl.SchemaUpdate - HHH000299: Could not complete schema update
org.hibernate.MappingException: No Dialect mapping for JDBC type: 90022
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:87) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:118) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.dialect.Dialect.getTypeName(Dialect.java:330) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.mapping.Column.getSqlType(Column.java:230) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.mapping.Table.sqlCreateString(Table.java:512) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.generateSchemaUpdateScriptList(Configuration.java:1207) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:237) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:203) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:522) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.grails.orm.hibernate.cfg.GrailsAnnotationConfiguration.buildSessionFactory(GrailsAnnotationConfiguration.java:390) ~[grails-datastore-gorm-hibernate4-4.0.4.RELEASE.jar:na]

**Comment by lmivan** [comment]
Hi.

Could you please answer the following questions?

- Version of the plugin are you using
- Grails 2 or Grails 3
- Postgres version

Thanks

**Comment by wolandec** [comment]
Yes.

* 4.6.1
* Grails 3.0.8
* Postgresql 9.4.4

**Comment by lmivan** [comment]
Great. Let me please do some tests and I'll try to get back as soon as possible.

**Comment by wolandec** [comment]
Thank for your attend!

**Comment by lmivan** [comment]
Hi.

I've created an empty Grails 3.0.8 application and then added the plugin and created a domain class as specified in the documentation.
When I run the app everything is working:

```
$ gradle bootRun
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:findMainClass
:bootRun
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: drop table test_map_jsonb cascade
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - ERROR: table "test_map_jsonb" does not exist
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: drop sequence seq_test_map_jsonb
ERROR org.hibernate.tool.hbm2ddl.SchemaExport - ERROR: sequence "seq_test_map_jsonb" does not exist
Grails application running at http://localhost:8080 in environment: development
```

I've uploaded the example app to github. You can see the modified files in this commit: https://github.com/lmivan/pg-extensions-grails3-jsonb-example-app/commit/96c34977aab9656748879c1d81a6d8057bcb615d

**Comment by ilopmar** [comment]
As Bobby Warner pointed me on the slack channel, it seems there's a very similar problem when running dbmigrations.

`
Command execution error: liquibase.command.CommandExecutionException: org.hibernate.MappingException: No Dialect mapping for JDBC type: 90021
`

**Comment by ilopmar** [comment]
It's a problem with the configuration of the dialect. Please check the documentation: https://github.com/kaleidos/grails-postgresql-extensions#configuration
