### ISSUE TITLE
How to use >=4.6.5 with grails 2.5?

### ISSUE THREAD

**Issue by edwardotis** [kaleidos/grails-postgresql-extensions#88]
Is grails 2 still supported? 

dependency 
        compile 'org.grails.plugins:postgresql-extensions:4.6.5'

grails compile --stacktrace

| Error Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at grails.util.BuildSettings.doResolve(BuildSettings.groovy:513)
	at grails.util.BuildSettings.doResolve(BuildSettings.groovy)
	at grails.util.BuildSettings$_getDefaultCompileDependencies_closure15.doCall(BuildSettings.groovy:503)
	at grails.util.BuildSettings$_getDefaultCompileDependencies_closure15.doCall(BuildSettings.groovy)
	at grails.util.BuildSettings.getDefaultCompileDependencies(BuildSettings.groovy:496)
	at grails.util.BuildSettings.getCompileDependencies(BuildSettings.groovy:472)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 6 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 8 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
	... 9 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://jcenter.bintray.com with type  using the available layout factories: Maven2RepositoryLayoutFactory
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:111)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
	... 10 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Cannot access https://jcenter.bintray.com with type  using the available layout factories: Maven2RepositoryLayoutFactory
	at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:142)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:107)
	... 12 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Unsupported repository layout 
	at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory.newInstance(Maven2RepositoryLayoutFactory.java:64)
	at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:111)
	... 13 more
| Error Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory
| Error Could not transfer artifact org.grails.plugins:postgresql-extensions:jar:4.6.5 from/to jcenter (https://jcenter.bintray.com): Cannot access https://jcenter.bintray.com with type  using the available connector factories: BasicRepositoryConnectorFactory

**Comment by edwardotis** [comment]
ok, I see that it has to be this style, and using 4.6.1 as newest.
    plugins {
        compile ":postgresql-extensions:4.6.1"
}

**Comment by ilopmar** [comment]
The latest version for Grails 2.x is 4.6.1. You can check them here https://github.com/kaleidos/grails-postgresql-extensions#release-notes

**Comment by edwardotis** [comment]
Thanks, so does this mean that no new features or bug fixes with be available for grails 2.x? Or is there support for both grails 2 and grails 3 going forward?

**Comment by ilopmar** [comment]
There is support for both versions although I don't have plans to add important features to Grails 2.x, at least not from the beginning. 
Basically, the differences between version `4.6.1` and `4.6.5` are two new criterias for jsonb `contains` and `isContained`. The other changes are cleanups/refactors and Grails 3 related things.

Are you interested in any specific feature in Grails 2.x?
